<ips:template parameters="$app, $area, $id, $count, $small=FALSE" />
{{if member.member_id}}
	{{if member.following( $app, $area, $id )}}
		<a href="{url="app=core&module=system&section=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="following_this_member"}" data-ipsTooltip class="ipsButton ipsButton_positive {{if $small}}ipsButton_fullWidth ipsButton_small{{endif}} ipsType_blendLinks" data-role="followButton" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-check'></i><i class='fa fa-user'></i> {{if !$small}}{lang="following_member"}{{endif}} <i class='fa fa-caret-down'></i></a>
	{{else}}	
		<a href="{url="app=core&module=system&section=notifications&do=follow&follow_app={$app}&follow_area={$area}&follow_id={$id}"}" title="{lang="follow_this_member"}" data-ipsTooltip class="ipsButton {{if $small}}ipsButton_fullWidth ipsButton_small ipsButton_alternate{{else}}ipsButton_primary{{endif}} ipsType_blendLinks" data-role="followButton" data-ipsHover data-ipsHover-cache='false' data-ipsHover-onClick><i class='fa fa-plus'></i><i class='fa fa-user'></i> {{if !$small}}
&nbsp;{lang="follow_member"}{{endif}}</a>
	{{endif}}
{{endif}}