<ips:template parameters="$member, $types, $currentAppModule, $currentType, $table" />
{{if !\IPS\Request::i()->isAjax()}}
<div data-controller='core.front.profile.main'>
	{template="profileHeader" app="core" location="front" group="profile" params="$member, true"}
	<br>
	<div data-role="profileContent">
{{endif}}
		<div class="ipsColumns ipsColumns_collapsePhone">
			<div class="ipsColumn ipsColumn_wide">
				<div class="ipsSideMenu ipsAreaBackground_light ipsPad" id="modcp_menu" data-ipsTabBar data-ipsTabBar-contentArea='#elUserContent' data-ipsTabBar-itemselector=".ipsSideMenu_item" data-ipsTabBar-activeClass="ipsSideMenu_itemActive" data-ipsSideMenu>
					<h3 class="ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium">
						<a href="#user_content" class="ipsPad_double" data-action="openSideMenu"><i class="fa fa-bars"></i> &nbsp;{lang="user_content_type"}&nbsp;<i class="fa fa-caret-down"></i></a>
					</h3>
					<div>
						<ul class="ipsSideMenu_list">
							<li><a href="{$member->url()->setQueryString( array( 'do' => 'content', 'change_section' => 1 ) )}" class="ipsSideMenu_item {{if !$currentType}}ipsSideMenu_itemActive{{endif}}">{lang="all_activity"}</a></li>
						</ul>
						{{foreach $types as $app => $_types}}
							<h4 class='ipsSideMenu_subTitle'>{lang="module__{$app}"}</h4>
							<ul class="ipsSideMenu_list">
								{{foreach $_types as $key => $class}}
									<li><a href="{$member->url()->setQueryString( array( 'do' => 'content', 'type' => $key, 'change_section' => 1 ) )}" class="ipsSideMenu_item {{if $currentType == $key}}ipsSideMenu_itemActive{{endif}}">{lang="{$class::$title}_pl"}</a></li>
								{{endforeach}}
							</ul>
						{{endforeach}}
					</div>			
				</div>
			</div>
			<div class="ipsColumn ipsColumn_fluid" id='elUserContent'>
				{template="userContentSection" group="profile" app="core" params="$member, $types, $currentAppModule, $currentType, $table"}
			</div>
		</div>
{{if !\IPS\Request::i()->isAjax()}}
	</div>
</div>
{{endif}}