<ips:template parameters="$record, $category, $database, $page, $title, $hasModOptions, $id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" original_group="form" key="database_form_recordForm" />
{{$modOptions = array( 'create_record_state', 'record_expiry_date', 'record_pinned', 'record_allow_comments', 'record_comment_cutoff' );}}
{template="pageHeader" if="!\IPS\Request::i()->isAjax()" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack( $title )"}
<hr class='ipsHr'>
<form accept-charset='utf-8' class="ipsForm {$class}" data-ipsForm="true" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
		<input type="hidden" name="content_record_form_container" value="{$category->_id}">
	{{endif}}

	{{if count( $elements ) > 1}}
	<div class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="topic_information"}</h2>
		<div class='ipsTabs ipsTabs_contained ipsClearfix ipsJS_show' id='tabs_{$id}' data-ipsTabBar data-ipsTabBar-contentArea='#ipsTabs_content_{$id}'>
			<a href='#tabs_{$id}' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
			<ul role='tablist'>
				{{foreach $elements as $name => $content}}
					<li role='presentation'>
						<a href='#ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' id='{$id}_tab_{$name}' class="ipsTabs_item">
							{lang="$name"}
						</a>
					</li>
				{{endforeach}}
			</ul>
		</div>
		<div id='ipsTabs_content_{$id}' class='ipsTabs_panels ipsTabs_contained'>
			{{foreach $elements as $name => $contents}}
				<div id='ipsTabs_tabs_{$id}_{$id}_tab_{$name}_panel' class="ipsTabs_panel ipsPad" aria-labelledby="{$id}_tab_{$name}" aria-hidden="false">
					<ul class='ipsForm ipsForm_vertical'>
						{{foreach $contents as $inputName => $input}}
							{{if !in_array( $inputName, $modOptions )}}
								{$input|raw}
							{{endif}}
						{{endforeach}}
					</ul>
				</div>
			{{endforeach}}
		</div>		
	{{else}}
		<div class="ipsPad">
		{{if $hasModOptions}}
			<div class='ipsColumns ipsColumns_collapsePhone'>
				<div class='ipsColumn ipsColumn_fluid'>
		{{endif}}
			<ul class='ipsForm ipsForm_vertical'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $inputName => $input}}
						{{if !in_array( $inputName, $modOptions ) and ( ! ( $inputName == 'content_field_' . $database->field_title and isset( $collection['record_static_furl_set'] ) and isset( $collection['record_static_furl'] ) ) ) and $inputName !== 'record_static_furl_set' and $inputName !== 'record_static_furl'}}
							{$input|raw}
						{{endif}}
						{{if $inputName == 'content_field_' . $database->field_title and isset( $collection['record_static_furl_set'] ) and isset( $collection['record_static_furl'] )}}
						<li class='ipsFieldRow ipsClearfix'>
							<label class="ipsFieldRow_label" for="{inputName}">{lang="$input->name"}</label>
							<div class='ipsFieldRow_content'>
								<input type="text" name="{$input->name}" value="{$input->value}" id="elInput_{$input->name}">
								{template="customslug" location="global" group="records" params="$collection, $input, $category, $page, $database, $record"}
							</div>
						</li>
						{{endif}}
					{{endforeach}}
				{{endforeach}}
			</ul>
			{{if $hasModOptions}}
			</div>
				<div class='ipsColumn ipsColumn_wide'>
					<div class='ipsPad ipsAreaBackground_light'>
					<h3 class='ipsType_sectionHead'>{lang="topic_moderator_options"}</h3>
						<ul class='ipsForm ipsForm_vertical ipsSpacer_top'>
							{{foreach $elements as $collection}}
								{{foreach $collection as $inputName => $input}}
									{{if in_array( $inputName, $modOptions )}}
										{{if $inputName == 'record_expiry_date' or $inputName == 'record_comment_cutoff'}}
											<li class='ipsFieldRow ipsClearfix'>
												<label class="ipsFieldRow_label" for="{inputName}">{lang="$input->name"}</label>
												<ul class='ipsFieldRow_content ipsList_reset cCreateTopic_date'>
													<li>
														<i class='fa fa-calendar'></i>
														<input type="date" name="{$input->name}" value="" class="ipsField_short" data-control="date" placeholder='{expression="mb_strtoupper( str_replace( 'y', 'yy', \IPS\Member::loggedIn()->language()->preferredDateFormat() ) )"}'>
													</li>
													<li>
														<i class='fa fa-clock-o'></i>
														<input name="{$input->name}_time" type="time" size="12" class="ipsField_short" placeholder="HH:MM" step="60" min="00:00">
													</li>
												</ul>
											</li>
										{{else}}
											{$input|raw}
										{{endif}}
									{{endif}}
								{{endforeach}}
							{{endforeach}}
						</ul>
					</div>
				</div>
			</div>
		{{endif}}
		</div>
	{{endif}}

	

		<br>
		<div class='ipsAreaBackground ipsPad ipsType_center'>
			<button type='submit' class='ipsButton ipsButton_large ipsButton_primary'>{lang="content_record_form_save"}</button>
		</div>
	</div>
</form>