<ips:template parameters="$rows, $uniqid, $sortData=array(), $root=false" />
{{if count( $rows )}}
	<ul class='ipsTree ipsTree_node'>
		{{foreach $rows as $id => $row}}
			<li id="sortable-{$uniqid}_{$id}" data-role="node" {{if isset( $sortData[ $id ] )}}data-sorttype='{$sortData[ $id ]['key']}' data-sortconnect='{$sortData[ $id ]['target']}'{{endif}}>
				{$row|raw}
			</li>
		{{endforeach}}	
	</ul>
{{endif}}