<ips:template parameters="$table, $headers, $rows, $quickSearch" />
<div data-baseurl='{$table->baseUrl}' data-resort='{$table->resortKey}' data-controller='core.global.core.table{{if $table->canModerate()}},core.front.core.moderation{{endif}}'>
	<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear">
		<ul class="ipsButtonRow ipsPos_right ipsClearfix">
			<li>
				<a href="#elSortByMenu_menu" id="elSortByMenu" data-role="sortButton" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="sort_by"} <i class="fa fa-caret-down"></i></a>
				<ul class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide" id="elSortByMenu_menu">
					<li class="ipsMenu_item {{if $table->sortBy == 'running_time'}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="running_time"><a href="{$table->baseUrl->setQueryString( array( 'filter' => $table->filter, 'sortby' => 'running_time', 'sortdirection' => 'desc', 'page' => '1', 'group' => \IPS\Request::i()->group ) )}">{lang="{$table->langPrefix}running_time"}</a></li>
					<li class="ipsMenu_item {{if $table->sortBy == 'member_name'}}ipsMenu_itemChecked{{endif}}" data-ipsMenuValue="member_name"><a href="{$table->baseUrl->setQueryString( array( 'filter' => $table->filter, 'sortby' => 'member_name', 'sortdirection' => 'asc', 'page' => '1', 'group' => \IPS\Request::i()->group ) )}">{lang="{$table->langPrefix}member_name"}</a></li>
				</ul>
			</li>

			{{if !empty( $table->filters )}}
				<li>
					<a href="#elFilterByMenu_{$table->uniqueId}_menu" data-role="tableFilterMenu" id="elFilterByMenu_{$table->uniqueId}" data-ipsMenu data-ipsMenu-activeClass="ipsButtonRow_active" data-ipsMenu-selectable="radio">{lang="filter_by"} <i class="fa fa-caret-down"></i></a>
					<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsMenu_selectable ipsHide' id='elFilterByMenu_{$table->uniqueId}_menu'>
						<li data-action="tableFilter" data-ipsMenuValue='' class='ipsMenu_item {{if !$table->filter}}ipsMenu_itemChecked{{endif}}'>
							<a href='{$table->baseUrl->setQueryString( array( 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection, 'page' => '1', 'filter' => '', 'group' => \IPS\Request::i()->group ) )}' class='{{if !array_key_exists( $table->filter, $table->filters )}}ipsButtonRow_active{{endif}}'>{lang="all"}</a>
						</li>
						{{foreach $table->filters as $k => $q}}
							<li data-action="tableFilter" data-ipsMenuValue='{$k}' class='ipsMenu_item {{if $k === $table->filter}}ipsMenu_itemChecked{{endif}}'>
								<a href='{$table->baseUrl->setQueryString( array( 'filter' => $k, 'sortby' => $table->sortBy, 'sortdirection' => $table->sortDirection, 'page' => '1', 'group' => \IPS\Request::i()->group ) )}'>{lang="{$table->langPrefix}{$k}"}</a>
							</li>
						{{endforeach}}
					</ul>
				</li>
			{{endif}}
		</ul>
		{{if $table->pages > 1}}
			<div data-role="tablePagination">
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
			</div>
		{{endif}}
	</div>

	<ol class='ipsList_reset ipsPad ipsGrid ipsGrid_collapsePhone ipsClear' data-ipsGrid data-role='tableRows'>
		{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
	</ol>

	{{if $table->pages > 1}}
		<div class="ipsButtonBar ipsPad_half ipsClearfix ipsClear" data-role="tablePagination">
			{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
		</div>
	{{endif}}
</div>