<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}
	
	<ul class='ipsForm ipsForm_vertical'>
		{{foreach $elements as $collection}}
			{{foreach $collection as $inputName => $input}}
				{{if $inputName == 'event_dates'}}
					{$input->html()|raw}
				{{endif}}
			{{endforeach}}
		{{endforeach}}
	</ul>
	<br>

	<div class='ipsBox'>
		<ul class='ipsForm ipsPad ipsForm_vertical'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $inputName => $input}}
					{{if $inputName != 'event_dates'}}
						{$input|raw}
					{{endif}}
				{{endforeach}}
			{{endforeach}}
		</ul>
		<br>
		<div class='ipsAreaBackground ipsPad ipsType_center'>
			<button type='submit' class='ipsButton ipsButton_large ipsButton_primary'>{lang="submit_event"}</button>
		</div>
	</div>
</form>