<ips:template parameters="" />
<section class='ipsType_center ipsPad ipsBox'>
	<br>
	<i class='ipsType_huge fa fa-lock'></i>
	<h1 class='ipsType_veryLarge'>{lang="reg_admin_validation"}</h1>

	<p class='ipsType_large'>
		{lang="reg_admin_validation_desc" sprintf="\IPS\Member::loggedIn()->email"}
	</p>
	{{$guest = new \IPS\Member;}}
	<p class='ipsType_normal'>
		<a href='{url="app=core&module=system&controller=login&do=logout" csrf="true" seoTemplate="logout"}' class='ipsButton ipsButton_primary'>{{if $guest->group['g_view_board']}}{lang="reg_continue_as_guest"}{{else}}{lang="sign_out"}{{endif}}</a>
	</p>
	<hr class='ipsHr'>
	<p class='ipsType_normal'>
		<a href='{url="app=core&module=system&controller=register&do=changeEmail" seoTemplate="register"}' data-ipsDialog data-ipsDialog-modal='true' class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="reg_change_email"}</a>
		<a href='{url="app=core&module=system&controller=register&do=cancel" csrf="true" seoTemplate="register"}' class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="reg_cancel"}</a>
	</p>
</section>