<ips:template parameters="$validating=array()" />
<section class='ipsType_center ipsPad'>
	<br><br>
	<i class='ipsType_huge fa fa-envelope'></i>
	<h1 class='ipsType_veryLarge'>{lang="reg_confirm_email"}</h1>

	<p class='ipsType_large'>
		{lang="reg_confirm_email_desc" sprintf="\IPS\Member::loggedIn()->email"}
	</p>
	<p class='ipsType_large'>
		{lang="reg_confirm_email_must"}
	</p>
	<hr class='ipsHr'>
	<p class='ipsType_normal'>
		<a href='{url="app=core&module=system&controller=register&do=resend" seoTemplate="register"}' class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="reg_resend_email"}</a>
		<a href='{url="app=core&module=system&controller=register&do=changeEmail" seoTemplate="register"}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="reg_change_email"}' data-ipsDialog-modal='true' class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="reg_change_email"}</a>
		<a href='{url="app=core&module=system&controller=login&do=logout" csrf="true" seoTemplate="logout"}' class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="sign_out"}</a>
		{{if $validating['new_reg']}}
			<a href='{url="app=core&module=system&controller=register&do=cancel" csrf="true" seoTemplate="register"}' class='ipsButton ipsButton_light ipsButton_verySmall'>{lang="reg_cancel"}</a>
		{{endif}}
	</p>
</section>