<ips:template parameters="$form" />
<h2 class='ipsType_sectionHead'>{lang="change_email_address"}</h2>
<br><br>
{{if \IPS\Settings::i()->reg_auth_type == 'user' or \IPS\Settings::i()->reg_auth_type == 'admin_user'}}
	<div class='ipsType_textBlock ipsType_normal'>
		<ul class='ipsList_bullets'>
			<li>{lang="change_email_explain_1"}</li>
			<li>
				{lang="change_email_explain_2"}
			</li>
		</ul>
	</div>
	<br><hr class='ipsHr'><br>
{{endif}}
{$form|raw}