<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}
	<div class='ipsComposeArea ipsComposeArea_withPhoto ipsClearfix'>
		<div class='ipsPos_left ipsResponsive_hidePhone ipsResponsive_block'>{template="userPhoto" app="core" group="global" params="\IPS\Member::loggedIn(), 'small'"}</div>
		<div class='ipsComposeArea_editor'>
			{{if !\IPS\Member::loggedIn()->member_id}}
				<div data-ipsEditor-toolList class='ipsMessage ipsMessage_info'>
					{lang="commenting_as_guest"}
				</div>
			{{endif}}
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if $input->name == 'guest_name'}}
						<ul class='ipsForm ipsForm_horizontal' data-ipsEditor-toolList>
							<li class='ipsFieldRow ipsFieldRow_fullWidth'>{$input->html()|raw}</li>
						</ul>
					{{endif}}
				{{endforeach}}
			{{endforeach}}
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{{if $input instanceof \IPS\Helpers\Form\Editor}}
						{$input->html( TRUE )|raw}
						{{if $input->error}}
							<br>
							<span class="ipsType_warning">{lang="$input->error"}</span>
						{{endif}}
					{{endif}}
				{{endforeach}}
			{{endforeach}}
			<ul class='ipsToolList ipsToolList_horizontal ipsClear ipsClearfix' data-ipsEditor-toolList>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{{if !($input instanceof \IPS\Helpers\Form\Editor) && $input->name != 'guest_name'}}
							<li class='ipsPos_left ipsResponsive_noFloat {{if !($input instanceof \IPS\Helpers\Form\Captcha)}}ipsComposeArea_formControl{{endif}} ipsType_small'>{$input->html()|raw}</li>
						{{endif}}
					{{endforeach}}
				{{endforeach}}
				{{foreach $actionButtons as $button}}
					<li>{$button|raw}</li>
				{{endforeach}}
			</ul>
		</div>
	</div>
</form>