<ips:template parameters="$warnings=array(),$ends=NULL" />
<div class="ipsMessage ipsMessage_warning">
	<p class='ipsType_reset'>{lang="mod_queue_message"}</p>
	{{if count( $warnings) AND ( !is_null( $ends ) AND $ends > 0 ) }}
		{{if count( $warnings )}}
			{lang="this_will_be_moderated"}
		{{endif}}
		{{if !is_null( $ends ) AND $ends > 0}}
			{lang="restriction_ends" sprintf="\IPS\DateTime::ts( $ends )->relative()"}
		{{endif}}
		{{foreach $warnings as $idx => $warning}}
			{{if $idx === 0}}
				<br><br>
				<a href="{$warning->url()}" class='ipsButton ipsButton_verySmall ipsButton_light' data-ipsDialog data-ipsDialog-size='narrow'>{lang="view_warning_details"}</a>
			{{endif}}
		{{endforeach}}
	{{endif}}
</div>