<ips:template parameters="$label, $element, $desc, $warning, $required=FALSE, $error=NULL, $prefix=NULL, $suffix=NULL, $id=NULL, $object=NULL, $form=NULL" />
<li class='ipsFieldRow{{if $object === NULL}} ipsFieldRow_textValue{{endif}}{{if $object instanceof \IPS\Helpers\Form\Checkbox and !( $object instanceof \IPS\Helpers\Form\YesNo )}} ipsFieldRow_checkbox{{endif}} ipsClearfix {{if $error}}ipsFieldRow_error{{endif}}' {{if $id}}id="{$id}"{{endif}}>
	{{if $object instanceof \IPS\Helpers\Form\Checkbox and !( $object instanceof \IPS\Helpers\Form\YesNo )}}
		{$prefix|raw}
		{$element|raw}
		{$suffix|raw}
		<div class='ipsFieldRow_content'>
			<label class='ipsFieldRow_label' for='check_{$id}'>{$label|raw} {{if $required}}<span class='ipsFieldRow_required'>{lang="required"}</span>{{endif}}</label>
			{$desc|raw}
			{$warning|raw}
			{{if $error}}
				<br>
				<span class="ipsType_warning">{lang="$error"}</span>
			{{endif}}
		</div>
	{{else}}
		{{if $label}}
			<label class='ipsFieldRow_label' {{if $object !== NULL}}for='{$object->name}'{{endif}}>
				{$label|raw} {{if $required}}<span class='ipsFieldRow_required'>{lang="required"}</span>{{endif}}
			</label>
		{{endif}}
		<div class='ipsFieldRow_content'>
			{$prefix|raw}
			{$element|raw}
			{$suffix|raw}
			{$desc|raw}
			{$warning|raw}
			{{if $error}}
				<br>
				<span class="ipsType_warning">{lang="$error"}</span>
			{{endif}}
		</div>
	{{endif}}
</li>