<ips:template parameters="$html, $title=NULL" original_group="custom_wrappers" key="page_custom_wrappers_customWrapper" />
<!DOCTYPE html>
<html lang="{expression="mb_substr( \IPS\Member::loggedIn()->language()->short, 0, 2 )"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
	<head>
		<title>{expression="output.getTitle( $title )"}</title>
		{template="includeMeta" app="core" group="global" location="global" params=""}
		{template="includeCSS" app="core" group="global" location="global" params=""}
		{template="includeJS" app="core" group="global" location="global" params=""}
	</head>
	<body class="ipsApp ipsApp_front ipsJS_none ipsClearfix ipsLayout_noBackground">
		{$html|raw}
	</body>
</html>