<ips:template parameters="$kb" />
<div class="ipsColumns ipsColumns_collapsePhone">
	<div class="ipsColumn ipsColumn_fluid">
		{{if \IPS\Member::loggedIn()->hasAcpRestriction( 'core', 'support', 'get_support' )}}
			<a href="{url="app=core&module=support&controller=support&_new=1"}" class="ipsButton ipsButton_veryLarge ipsButton_important ipsButton_fullWidth">{lang="get_support"}</a>
			<br><br>
		{{endif}}
		{{if count( $kb )}}
			<h2 class="ipsType_sectionTitle">{lang="latest_knowledgebase_articles"}</h2>
			<ul class='ipsDataList'>
			{{foreach $kb as $v}}
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic">
						<a href="{$v['link']}" target="_blank">{$v['title']}</a>
					</span>
				</li>
			{{endforeach}}
		{{endif}}
	</div>
	<div class="ipsColumn ipsColumn_veryWide">
		<h2 class="ipsType_sectionTitle">{lang="system_information"}</h2>
		<div class="ipsOverflow">
			<ul class='ipsDataList'>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="php_version"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{expression="PHP_VERSION"}<br>
						<a href="{url="app=core&module=support&controller=dashboard&do=phpinfo"}" class="ipsType_small ipsType_light">phpinfo</a>
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="mysql_version"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{expression="\IPS\Db::i()->server_info"}
						{{if \IPS\Member::loggedIn()->hasAcpRestriction( 'core', 'support', 'sql_toolbox' )}}
							<br>
							<a href="{url="app=core&module=support&controller=sql"}" class="ipsType_small ipsType_light">{lang="sql_toolbox"}</a>
						{{endif}}
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="server_path"}</strong>
					</span>
					<span class="ipsDataItem_generic ipsType_small">
						{expression="\IPS\ROOT_PATH"}
					</span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic ipsDataItem_size4">
						<strong class="title">{lang="server_ip"}</strong>
					</span>
					<span class="ipsDataItem_generic">
						{$_SERVER['SERVER_ADDR']}
					</span>
				</li>
			</ul>
		</div>
		<br><br>
		<h2 class="ipsType_sectionTitle">{lang="diagnostic_logs"}</h2>
		<div class="ipsOverflow">
			<ul class='ipsDataList'>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic"><a href="{url="app=core&module=support&controller=errorLogs"}">{lang="error_logs"}</a></span>
				</li>
				<li class="ipsDataItem">
					<span class="ipsDataItem_generic"><a href="{url="app=core&module=support&controller=systemLogs"}">{lang="system_logs"}</a></span>
				</li>
			</ul>
		</div>
	</div>
</div>