<ips:template parameters="$application" />
<div class='ipsPad ipsAreaBackground ipsType_center'>
	<a href='{url="app=core&module=applications&controller=applications&appKey={$application}&do=download&type=build"}' class='ipsButton'>{lang="app_buildanddownload"}</a>
	<a href='{url="app=core&module=applications&controller=applications&appKey={$application}&do=download&type=download"}' class='ipsButton ipsButton_alternate'>{lang="app_justdownload"}</a>
</div>