<ips:template parameters="$event" />
<div class='' data-controller='core.front.core.commentFeed' data-baseURL='{$event->url()}' {{if $event->isLastPage()}}data-lastPage{{endif}} data-feedID='event-{$event->id}'>
	{{if $event->commentPageCount() > 1}}
		{$event->commentPagination( array( 'tab' ) )|raw}
		<br><br>
	{{endif}}
	<div data-role='commentFeed' data-controller='core.front.core.moderation'>
		{{if ( $comments = $event->comments() and count( $comments ) )}}
			<form action="{$event->url()->setQueryString( 'do', 'multimodComment' )}" method="post" data-ipsPageAction data-role='moderationTools'>
				{{$commentCount=0; $firstUnread = $event->firstUnreadComment();}}
				{{foreach $comments as $comment}}
					{{if $commentCount and $firstUnread and $firstUnread == $comment}}
						<hr class="ipsCommentUnreadSeperator">
					{{endif}}
					{{$commentCount++;}}
					{$comment->html()|raw}
				{{endforeach}}
				{template="commentMultimod" app="core" group="global" params="$event"}
			</form>
		{{else}}
			<p class='ipsType_normal ipsType_light ipsType_center' data-role='noComments'>{lang="no_comments"}</p>
		{{endif}}
	</div>
	{{if $event->commentPageCount() > 1}}
		<hr class='ipsHr'>
		{$event->commentPagination( array( 'tab' ) )|raw}
	{{endif}}
	{{if $event->canComment() || $event->locked() || \IPS\Member::loggedin()->restrict_post || \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
		<br><br>
		<div class='ipsAreaBackground ipsPad ipsClear' data-role='replyArea'>
			{{if $event->canComment()}}
				{{if $event->locked()}}
					<strong class='ipsType_warning ipsComposeArea_warning'><i class='fa fa-info-circle'></i> {lang="event_locked_can_comment"}</strong>
				{{endif}}
				{$event->commentForm()|raw}
			{{else}}
				{{if $event->locked()}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'event_locked_cannot_comment'"}
				{{elseif \IPS\Member::loggedin()->restrict_post}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
				{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
				{{endif}}
			{{endif}}
		</div>
	{{endif}}
</div>