<ips:template parameters="$value, $key, $lang, $js" />
<a href="{url="app=core&module=languages&controller=languages&do=translateWord&key={$key}&lang={$lang}&js={$js}"}" data-controller="core.admin.core.langString">{$value}</a>
{{if !$value}}
	<noscript>
		<em><a href="{url="app=core&module=languages&controller=languages&do=translateWord&key={$key}&lang={$lang}&js={$js}"}">{lang="no_value"}</a></em>
	</noscript>
{{endif}}