<ips:template parameters="$name, $memberId" />
<div class="ipsJS_hide">
	<input name="{$name}" autocomplete="off"><br>
	<span class="ipsType_light">{lang="members_pass_change"}</span>
</div>
<div class="ipsJS_show">
	<span class='ipsType_light'>{lang="password_hidden"}</span><br>
	<a href="{url="app=core&module=members&controller=members&do=password&id={$memberId}"}" data-ipsDialog data-ipsDialog-title="{lang="change_password"}">{lang="change_password"}</a>
</div>