<ips:template parameters="$name, $value" />
{lang="after"}
<input type="number" name="{$name}[0]" value="{{if isset( $value[0] )}}{$value[0]}{{endif}}">
<select name="{$name}[1]">
	<option value="0" {{if isset( $value[1] ) and !$value[1]}}selected="selected"{{endif}}>{lang="approved_posts_comments"}</option>
	<option value="1" {{if isset( $value[1] ) and $value[1]}}selected="selected"{{endif}}>{lang="days_since_joining"}</option>
</select>
&nbsp; {lang="or"} &nbsp;
<input type="checkbox" data-control="unlimited" id='el{$name}_unlimited' {{if !isset( $value[0] ) or !$value[0]}}checked="checked"{{endif}} name="{$name}[2]"> <label for='el{$name}_unlimited' class='ipsField_unlimited'>{lang="never"}</label>