<ips:template parameters="$files, $pagination, $url" />
{{if empty($files)}}
	<div class='ipsPad ipsAreaBackground_light'>
		{lang="no_results"}
	</div>
{{else}}
	<div class="ipsGrid ipsAttachment_fileList">
		{{foreach $files as $url => $file}}
			{template="uploadFile" group="forms" location="global" params="$url, $file, NULL, TRUE, FALSE, $url"}
		{{endforeach}}
	</div>
	<br>
	{$pagination|raw}
{{endif}}
