<ips:template parameters="$id, $widgets, $orientation='horizontal'" />
{{if ( ( isset( $widgets[ $id ] ) ) || \IPS\Dispatcher::i()->application->canManageWidgets() )}}
	<div class='cWidgetContainer {{if ! isset( $widgets[ $id ] )}}ipsHide{{endif}}' {{if \IPS\Dispatcher::i()->application->canManageWidgets()}}data-controller='core.front.widgets.area'{{endif}} data-role='widgetReceiver' data-orientation='{$orientation}' data-widgetArea='{$id}'>
		<ul class='ipsList_reset'>
			{{if isset( $widgets[ $id ] )}}
				{{foreach $widgets[ $id ] as $widget}}
				<li class='ipsWidget ipsWidget_{$orientation}' data-blockTitle="{$widget->title()}" data-blockID='{{if isset($widget->app)}}app_{$widget->app}_{{else}}plugin_{$widget->plugin}_{{endif}}{$widget->key}_{$widget->uniqueKey}'{{if $widget->hasConfiguration()}} data-blockConfig="true"{{endif}} data-controller='core.front.widgets.block'>{$widget|raw}</li>
				{{endforeach}}
			{{endif}}
		</ul>
	</div>
{{endif}}