<ips:template parameters="" />
{{foreach array_unique( \IPS\Output::i()->cssFiles, SORT_STRING ) as $file}}
	<link rel='stylesheet' href='{expression="\IPS\Http\Url::external( $file )->setQueryString( 'v', \IPS\SUITE_UNIQUE_KEY )"}' media='all'>
{{endforeach}}
{{if \IPS\IN_DEV or \IPS\Theme::designersModeEnabled()}}
	{{if $delayed = \IPS\Theme\Dev\Theme::getDelayedCss()}}
		{{foreach $delayed as $file}}
			<link rel='stylesheet' href='{expression="\IPS\Http\Url::external( $file )->setQueryString( 'v', \IPS\SUITE_UNIQUE_KEY )"}' media='all'>
		{{endforeach}}
	{{endif}}
{{endif}}
{{if \IPS\Dispatcher::i()->controllerLocation === 'front' }}
	{{$customCss = \IPS\Theme::i()->css( 'custom.css', 'core', 'front' );}}
	<link rel='stylesheet' href='{expression="\IPS\Http\Url::external( array_pop( $customCss ) )->setQueryString( 'v', \IPS\SUITE_UNIQUE_KEY )"}' media='all'>
{{endif}}
{{if \IPS\Output::i()->headCss}}
<style type='text/css'>
	{expression="\IPS\Output::i()->headCss" raw="true"}
</style>
{{endif}}