<ips:template parameters="$topics, $orientation='vertical'" />
{{if !empty( $topics ) }}
<h3 class='ipsWidget_title ipsType_reset'>{lang="block_featuredTopics"}</h3>

{{if $orientation == 'vertical'}}
<div class='ipsPad_half ipsWidget_inner'>

	<ul class='ipsDataList ipsDataList_reducedSpacing'>
		{{foreach $topics as $topic}}
		<li class='ipsDataItem'>
			<div class='ipsDataItem_icon ipsPos_top'>
				{template="userPhoto" group="global" app="core" params="$topic->author(), 'tiny'"}
			</div>
			<div class='ipsDataItem_main'>
				<div class="ipsCommentCount ipsPos_right {{if ( $topic->posts - 1 ) === 0}}ipsFaded{{endif}}" data-ipsTooltip title='{lang="replies_number" pluralize="$topic->posts - 1"}'>{expression="$topic->posts - 1"}</div>
				<a href="{$topic->url()}" title='{lang="view_this_topic" sprintf="$topic->title"}' class='ipsDataItem_title ipsType_break'>{lang="$topic->title" wordbreak="true"}</a><br>
				<span class='ipsType_light ipsType_small'>{lang="byline_nodate" htmlsprintf="$topic->author()->link()"} &middot; {lang="topic_started_date" htmlsprintf="\IPS\DateTime::ts( $topic->mapped('date') )->html()"}</span>
			</div>
		</li>
		{{endforeach}}
	</ul>
</div>
{{else}}
<div class='ipsWidget_inner'>
	<ul class='ipsDataList'>
		{{foreach $topics as $topic}}
		{template="row" group="global" app="forums" params="NULL, NULL, $topic, FALSE"}
		{{endforeach}}
	</ul>
</div>
{{endif}}
{{endif}}