<ips:template parameters="$url, $pagination, $followers, $anonymous" />
<div data-ipsInfScroll data-ipsInfScroll-scrollScope="#elFollowerList" data-ipsInfScroll-container="#elFollowerList" data-ipsInfScroll-url="{$url}" data-ipsInfScroll-pageParam="followerPage" data-ipsInfScroll-pageBreakTpl="">
	<div class="ipsJS_hide">{$pagination|raw}</div>
	<div class='ipsFollowerList ipsPad ipsScrollbar'>
		<ul class="ipsDataList ipsList_reset" id="elFollowerList">
			{template="followersRows" group="system" params="$followers"}
		</ul>
		{{if $anonymous}}
			{{if count( $followers )}}
				<div class="ipsPad_half ipsType_center ipsType_light">{lang="and_x_others" pluralize="$anonymous"}</div>
			{{else}}
				<div class="ipsPad_half ipsType_center ipsType_light">{lang="x_anonymous_members" pluralize="$anonymous"}</div>
			{{endif}}
		{{endif}}
	</div>
</div>