<ips:template parameters="$comment" />
<li class="ipsDataItem">
	<div class='ipsDataItem_icon ipsType_center ipsPos_top ipsResponsive_hidePhone'>
		{template="userPhoto" group="global" app="core" params="$comment->author(), 'tiny'"}
		<br><br>
		<i class="fa fa-comment ipsType_large ipsType_light" title="{lang="$comment::$title"}" data-ipsTooltip></i>
	</div>
	<div class='ipsDataItem_main'>
		<div class='ipsType_break ipsContained cSearchResultHighlight'>
			<h4 class='ipsType_sectionHead ipsContained'>
				<a href='{$comment->url()}' class='ipsType_blendLinks'><span class='ipsType_light'>{lang="$comment::$title"} {lang="on"}</span> {$comment->item()->mapped('title')}</a>
				{{if $container = $comment->item()->containerWrapper()}}
					<span class="ipsType_medium">{lang="in"} <a href="{$container->url()}">{$container->_title}</a></span>
				{{endif}}
				{{if $comment->hidden() or $comment->item()->hidden()}}
					<span>
						{{if $comment->hidden() === -1  or $comment->item()->hidden() === -1}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$comment->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
						{{elseif $comment->hidden() === 1 or  $comment->item()->hidden() === 1}}
							<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
						{{endif}}							
					</span>
				{{endif}}				
			</h4>		
			<span class='ipsType_medium ipsType_light ipsType_blendLinks'>{lang="search_posted_by" sprintf="ucfirst( \IPS\Member::loggedIn()->language()->get( '__indefart_' . $comment::$title ) )" htmlsprintf="$comment->author()->link()"} {datetime="$comment->mapped('date')"}</span>	
		</div>
		<div class="cSearchResultHighlight">
			{{$app = $comment::$application;}}
			{template="snippet" group="global" app="$app" params="$comment, 'search'"}
		</div>
	</div>
</li>