<ips:template parameters="$members, $memberCount, $orientation='vertical'" />

<h3 class='ipsType_reset ipsWidget_title'>
	{{if \IPS\Dispatcher::i()->application->directory !== 'core'}}
		{lang="block_activeUsers" sprintf="\IPS\Member::loggedIn()->language()->addToStack('__app_' . \IPS\Dispatcher::i()->application->directory )"}
	{{else}}
		{lang="block_activeUsers_noApp"}
	{{endif}}
	{{if $orientation == 'horizontal'}}
		&nbsp;&nbsp;<span class='ipsType_light ipsType_unbold ipsType_medium'>{lang="block_user_online_info" pluralize="$memberCount"}</span>
	{{endif}}
</h3>
<div class='ipsWidget_inner'>
	{{if $orientation == 'vertical'}}
		<div class='ipsPad'>
	{{endif}}
	{{if $memberCount}}
		<ul class='ipsList_inline ipsList_csv ipsList_noSpacing'>
			{{if \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'members' ) ) }}
				{{foreach $members as $row}}
					<li>
						<a href="{url="app=core&module=members&controller=profile&id={$row['member_id']}" seoTemplate="profile" seoTitle="$row['seo_name']"}" data-ipsHover data-ipsHover-target='{url="app=core&module=members&controller=profile&id={$row['member_id']}&do=hovercard" seoTemplate="profile" seoTitle="$row['seo_name']"}' title="{lang="view_user_profile" sprintf="$row['member_name']"}">{expression="\IPS\Member\Group::load( $row['member_group'] )->formatName( $row['member_name'] )" raw="true"}</a>
					</li>
				{{endforeach}}
			{{else}}
				{{foreach $members as $row}}
					<li>
						{expression="\IPS\Member\Group::load( $row['member_group'] )->formatName( $row['member_name'] )" raw="true"}
					</li>
				{{endforeach}}
			{{endif}}
		</ul>
		{{if $memberCount > 60 && $orientation == 'vertical'}}
			<p class='ipsType_medium ipsType_reset'>
				<a href='{url="app=core&module=online&controller=online" seoTemplate="online"}'>{lang="and_x_others" pluralize="$memberCount - 60"}</a>
			</p>
		{{endif}}
	{{else}}
		<p class='ipsType_reset ipsType_medium ipsType_light'>{lang="active_users_empty"}</p>
	{{endif}}
	{{if $orientation == 'vertical'}}
		</div>
	{{endif}}
</div>