<ips:template parameters="$stats, $orientation='vertical'" />
<h3 class='ipsType_reset ipsWidget_title'>{lang="block_stats"}</h3>
<div class='ipsWidget_inner'>
	{{if $orientation == 'vertical'}}
		<div class='ipsPad_half'>
			<ul class="ipsDataList">
				<li class="ipsDataItem">
					<div class="ipsDataItem_main ipsPos_middle">
						<strong>{lang="stats_total_members"}</strong>
					</div>
					<div class="ipsDataItem_stats ipsDataItem_statsLarge">
						<span class="ipsDataItem_stats_number">{number="$stats['member_count']"}</span>
					</div>
				</li>
				<li class="ipsDataItem">
					<div class="ipsDataItem_main ipsPos_middle">
						<strong>{lang="stats_most_online"}</strong>
					</div>
					<div class="ipsDataItem_stats ipsDataItem_statsLarge">
						<span class="ipsDataItem_stats_number">{number="$stats['most_online']['count']"}</span><br>
						<span class="ipsType_light ipsType_small"><time>{$stats['most_online']['time']}</time></span>
					</div>
				</li>
			</ul>
			<hr class='ipsHr'>
			{{if $stats['last_registered']}}
				<div class='ipsClearfix ipsPad_bottom'>
					<div class='ipsPos_left ipsType_center cNewestMember'>
						{template="userPhoto" app="core" group="global" params="$stats['last_registered'], 'small'"}
					</div>
					<div class='ipsWidget_latestItem'>
						<strong class='ipsType_minorHeading'>{lang="stats_newest_member"}</strong><br>
						<span class='ipsType_normal'>{$stats['last_registered']->link()|raw}</span><br>
						<span class='ipsType_medium ipsType_light'>{lang="members_joined"} <time>{$stats['last_registered']->joined->getTimestamp()}</time></span>
					</div>
				</div>
			{{endif}}
		</div>
	{{else}}
		<div class='ipsGrid ipsGrid_collapsePhone ipsWidget_stats'>
			<div class='ipsGrid_span4 ipsType_center'>
				<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['member_count']"}</span><br>
				<span class='ipsType_light ipsType_medium'>{lang="stats_total_members"}</span>
			</div>
			<div class='ipsGrid_span4 ipsType_center'>
				<span class='ipsType_large ipsWidget_statsCount' data-ipsTooltip title='<time data-norelative="true">{$stats['most_online']['time']}</time>'>{number="$stats['most_online']['count']"}</span><br>
				<span class='ipsType_light ipsType_medium'>{lang="stats_most_online"}</span>
			</div>
			<div class='ipsGrid_span4 ipsType_left ipsPhotoPanel ipsPhotoPanel_mini cNewestMember'>
				{template="userPhoto" app="core" group="global" params="$stats['last_registered'], 'mini'"}
				<div>
					<span class='ipsType_minorHeading'>{lang="stats_newest_member"}</span><br>
					<span class='ipsType_normal'>{$stats['last_registered']->link()|raw}</span><br>
					<span class='ipsType_small ipsType_light'>{lang="members_joined"} <time>{$stats['last_registered']->joined->getTimestamp()}</time></span>
				</div>
			</div>
		</div>
	{{endif}}
</div>