<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}
	{{foreach $elements as $collection}}
		{{foreach $collection as $input}}
			{{if $input->error}}
				<div class="ipsPad ipsAreaBackground_light">
					<p class='ipsMessage ipsMessage_error'>{lang="$input->error"}</p>
				</div>
			{{endif}}
		{{endforeach}}
	{{endforeach}}
	<section class='ipsAreaBackground_light ipsPad_half' id='elCodeHookEditor' data-controller='core.admin.system.codeHook'>
		<div class="ipsColumns ipsColumns_collapsePhone">
			<div class="ipsColumn ipsColumn_wide">
				{expression="array_pop( $sidebar )" raw="true"}
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				{{foreach $elements as $collection}}
					{{foreach $collection as $input}}
						{$input->html()|raw}
					{{endforeach}}
				{{endforeach}}
			</div>
		</div>

		<div class="ipsAreaBackground_light ipsClearfix ipsType_center">
			{{foreach $actionButtons as $button}}
				{$button|raw}
			{{endforeach}}
		</div>
	</section>
</form>