<ips:template parameters="$database, $records, $orientation='vertical'" original_group="" key="block_features_4_block_1151" />
{{if !empty( $records ) }}
	<div class="ipsGrid metalEdge_feature4Block">
	{{foreach $records as $record}}
		<div class="ipsGrid_span4 metalEdge_box ipsPad">
			<div class="metalEdge_featuredCover metalEdge_coverImage" style="background-image: url({$record->customFieldDisplayByKey('cover-image')|raw});">
				<!-- Image -->
			</div>
			<br>
			<a href="{$record->url()->setQueryString( 'do', 'getLastComment' )}" title='{lang="view_this_topic" sprintf="$record->title"}' class='ipsDataItem_title metalEdge_largeTitle ipsType_break' data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'>{lang="$record->_title" wordbreak="true"}</a>
			<br><span class='feature4Block_info'>{lang="byline_nodate" htmlsprintf="$record->author()->link()"} &middot; {datetime="$record->mapped('date')"}</span>
		</div>
	{{endforeach}}
		<div class="metalEdge_feature4Block_ad ipsGrid_span4 metalEdge_box ipsPad">
			<a href="#"><img src="/themes/2/images/280-ad.jpg" /></a>
		</div>
	</div>
{{endif}}
