<ips:template parameters="$database, $records, $orientation='vertical'" original_group="" key="block_RecordFeed_home_non_pinned_releases" />
{{if !empty( $records ) }}
<div class="ipsGrid metalEdge_reviews">
  {{foreach $records as $row}}
  <div class="ipsGrid_span3 metalEdge_non-releases">
          <div class="ipsCms_record_image">
              <img class="ipsImage" src="{$row->customFieldDisplayByKey('releases-album-art')|raw}" width="235" height="235">
          </div>
          <span class="metalEdge_rating rating_{$row->averageReviewRating()}">{$row->averageReviewRating()}</span>
          <a href="{$row->url()}">{$row->_title}</a>
          <br>
          {$row->customFieldDisplayByKey('artist')|raw}
  </div>
  {{endforeach}}
</div>
{{endif}}