<ips:template parameters="$database, $records, $orientation='vertical'" original_group="" key=" key="block_RecordFeed_home_archive_article" />
{{if !empty( $records ) }}
<div class="ipsGrid metalEdge_home-archive">
	{{foreach $records as $row}}
	<div class="ipsGrid_span8 metalEdge_box" style="background: url({$row->record_image}) no-repeat top center; background-size: cover; height: 630px">
		<div class="metalEdge_home-archive_overlay"></div>
          <div class="metalEdge_home-archive_info">
	          {$row->customFieldDisplayByKey('feature-teaser')|raw}
	          <a href="{$row->url()}">{$row->_title}</a>
	       </div>
	</div>
	{{endforeach}}
	<div class="ipsGrid_span4 metalEdge_home-archive_ad ipsPad">
			<a href="#"><img src="/themes/2/images/600-ad.jpg" /></a>
	</div>
</div>
{{endif}}