<ips:template parameters="$id, $nextId, $queries, $errors=NULL" />
<div class="ipsPad">
	{{if $errors === NULL}}
		{lang="database_changes_to_make"}
	{{else}}
		<div class="ipsMessage ipsMessage_warning">{lang="database_changes_to_make_errors"}</div>
	{{endif}}
	{{foreach $queries as $i => $query}}
		<pre class="prettyprint lang-sql cSupportQuery">{$query}</pre>
		{{if $errors !== NULL and isset( $errors[ $i ] )}}
			<span class='ipsType_warning'>{$errors[ $i ]}</span>
		{{endif}}
	{{endforeach}}
</div>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	{{if $errors === NULL}}
		<a href="{url="app=core&module=support&controller=support&next={$id}&mr=0&run=1"}" data-action="redirectContinue" class="ipsButton ipsButton_primary">{lang="database_changes_run"}</a>
	{{endif}}
	<a href="{url="app=core&module=support&controller=support&next={$id}&mr=0&recheck=1"}" data-action="redirectContinue" class="ipsButton ipsButton_alternate">{lang="database_changes_check_again"}</a>
	<a href="{url="app=core&module=support&controller=support&next={$nextId}&mr=0"}" data-action="redirectContinue" class="ipsButton ipsButton_alternate">{lang="continue_anyway"}</a>
</div>