<ips:template parameters="$name, $value" />
<select name="{$name}[0]">
	<option value="<" {{if $value[0] == '<'}}selected{{endif}}>{lang="greater_than"}</option>
	<option value=">" {{if $value[0] == '>'}}selected{{endif}}>{lang="less_than"}</option>
</select>
<input type="number" name="{$name}[1]" value="{$value[1]}" class="ipsField_short">
<select name="{$name}[2]">
	<option value="d" {{if $value[2] == 's'}}selected{{endif}}>{lang="days"}</option>
	<option value="m" {{if $value[2] == 'm'}}selected{{endif}}>{lang="months"}</option>
	<option value="y" {{if $value[2] == 'y'}}selected{{endif}}>{lang="years"}</option>
</select>
{lang="ago"} {lang="or"} <input type="checkbox" name="{$name}[3]" id='el{$name}_3' data-control="unlimited" {{if $value[3]}}checked{{endif}}> <label for='el{$name}_3' class='ipsField_unlimited'>{{if mb_strpos( $name, 'not' )}}{lang="no_restriction"}{{else}}{lang="any_time"}{{endif}}</label>