<ips:template parameters="$record" original_group="releases_display" key="database_releases_display_comments" />

<div data-controller='core.front.core.commentFeed' data-commentsType='comments' data-baseURL='{$record->url()}' {{if $record->isLastPage()}}data-lastPage{{endif}} data-feedID='record-{$record->_id}'>
	<br>
	{{if $record->commentPageCount() > 1}}
		{$record->commentPagination( array( 'tab' ) )|raw}
		<br><br>
	{{endif}}
	<div data-role='commentFeed' data-controller='core.front.core.moderation'>
		{{if count( $record->comments() )}}
			<form action="{$record->url()->setQueryString( 'do', 'multimodComment' )}" method="post" data-ipsPageAction data-role='moderationTools'>
				{{$commentCount=0; $timeLastRead = $record->timeLastRead(); $lined = FALSE;}}
				{{foreach $record->comments() as $comment}}
					{{if !$lined and $timeLastRead and $timeLastRead->getTimestamp() < $comment->mapped('date')}}
						{{if $lined = TRUE and $commentCount}}
							<hr class="ipsCommentUnreadSeperator">
						{{endif}}
					{{endif}}
					{{$commentCount++;}}
					{$comment->html()|raw}
				{{endforeach}}
				{template="commentMultimod" app="core" group="global" params="$record"}
			</form>
		{{else}}
			<p class='ipsType_normal ipsType_light ipsType_reset' data-role='noComments'>{lang="no_comments"}</p>
		{{endif}}
	</div>
	{{if $record->commentPageCount() > 1}}
		<hr class='ipsHr'>
		{$record->commentPagination( array( 'tab' ) )|raw}
	{{endif}}
	{{if $record->commentForm() || $record->locked() || \IPS\Member::loggedin()->restrict_post || \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
		<br><br>
		<div class='ipsAreaBackground ipsPad' data-role='replyArea'>
			{{if $record->commentForm()}}
				{{if $record->locked()}}
					<strong class='ipsType_warning ipsComposeArea_warning'><i class='fa fa-info-circle'></i> {lang="file_locked_can_comment"}</strong>
				{{endif}}
				{$record->commentForm()|raw}
			{{else}}
				{{if $record->locked()}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'file_locked_cannot_comment'"}
				{{elseif \IPS\Member::loggedin()->restrict_post}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'restricted_cannot_comment', \IPS\Member::loggedIn()->warnings(5,NULL,'rpa'), \IPS\Member::loggedIn()->restrict_post"}
				{{elseif \IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']}}
					{template="commentUnavailable" group="forms" location="front" app="core" params="'unacknowledged_warning_cannot_post', \IPS\Member::loggedIn()->warnings( 1, FALSE )"}
				{{endif}}
			{{endif}}
		</div>
	{{endif}}
</div>