<ips:template parameters="" />
<li class="ipsFieldRow">
	<div id="elPages_block_preview_wrapper">
		<iframe class='loading' src='{url="app=cms&module=pages&controller=builder&do=previewBlock" base="front"}' data-base-url="{url="app=cms&module=pages&controller=builder&do=previewBlock" base="front"}" frameborder="0" name="elpages_block_preview" id="elpages_block_preview"></iframe>
	</div>
	<div class="ipsPos_right">
		<span data-role="refreshPreview" class="ipsButton ipsButton_light ipsButton_small">{lang="cms_block_preview_refresh"}</span>
	</div>
	<br />
	<br />
<li>