<ips:template parameters="$record, $database" original_group="category_articles" key="database_category_articles_entry" />
<article class='cCmsCategoryFeaturedEntry {{if $record->hidden()}}ipsModerated{{endif}}'>
	<header class='ipsPhotoPanel ipsPhotoPanel_notPhone ipsPhotoPanel_small ipsSpacer_bottom'>
		{template="userPhoto" app="core" params="$record->author()" group="global"}
		<div> 
			<h2 class='ipsType_pageTitle'>
				{{if $record->prefix()}}
				{template="prefix" group="global" app="core" params="$record->prefix( TRUE ), $record->prefix()"}
				{{endif}}
				<a href="{$record->url()}" title='{lang="read_more_about" sprintf="$record->_title"}'>
					{{if $record->unread()}}
					<span class='ipsItemStatus' data-ipsTooltip title="{lang="cms_unread_record"}"><i class="fa fa-circle"></i></span>
					{{endif}}
					{lang="$record->_title" wordbreak="true"}
				</a>
				{{if $record->mapped('pinned') || $record->mapped('featured') || $record->hidden() === -1 || $record->hidden() === 1}}
				{{if $record->hidden() === -1}}
				<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$record->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
				{{elseif $record->hidden() === 1}}
				<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
				{{endif}}
				{{if $record->mapped('pinned')}}
				<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
				{{endif}}
				{{if $record->mapped('featured')}}
				<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
				{{endif}}
				{{endif}}
			</h2>
			<p class='ipsType_light ipsType_reset'>
				{lang="cms_byline" htmlsprintf="$record->author()->link(), $record->container()->url(), $record->container()->_title"}{datetime="$record->record_publish_date"}
			</p>
		</div>
	</header>

	<section class='ipsType_normal ipsType_richText ipsType_break ipsSpacer_both' data-ipsTruncate data-ipsTruncate-size='7 lines' data-ipsTruncate-type='remove'>
		{{if $record->record_image}}
		<div class="ipsCms_record_image">
			<img class="ipsImage" src="{$record->record_image}">
		</div>
		{{endif}}

		{$record->truncated()|raw}
	</section>
	{{if count( $record->tags() )}}
	{template="tags" group="global" app="core" params="$record->tags()"}
	{{endif}}
	<ul class='ipsList_inline'>
		<li><strong><a href='{$record->url()}' title='{lang="read_more_about" sprintf="$record->name"}'>{lang="read_more"}</a></strong></li>
		{{if \IPS\Settings::i()->blog_enable_rating}}
		<li>{template="rating" app="core" params="'small', $record->averageRating()" group="global"}</li>
		{{endif}}
		<li><a href='{$record->url()}#comments' title='{lang="view_comments"}'><i class='fa fa-comment'></i> {lang="num_comments" pluralize="$record->record_comments"}</a></li>
		<li class='ipsType_light'>{lang="num_views_with_number" pluralize="$record->record_views"}</li>
	</ul>
</article>