<ips:template parameters="$database, $articles, $url, $pagination" original_group="category_articles" key="database_category_articles_index" />
<div class='ipsPageHeader ipsClearfix ipsSpacer_bottom'>
	{{if $database->use_categories}}
	<div class='ipsPos_right ipsResponsive_noFloat'>
		<a href="{$url->setQueryString('show', 'categories')}" class="ipsButton ipsButton_medium ipsButton_fullWidth ipsButton_link"><i class="fa fa-folder-open"></i> {lang="cms_show_categories"}</a>
	</div>
	{{endif}}
	<h1 class='ipsType_pageTitle'>{$database->_title}</h1>
	{{if $database->_description}}
		<div class='ipsPageHeader_info ipsType_light'>
			{$database->_description}
		</div>
	{{endif}}
</div>
<hr class='ipsHr'>
<section class='ipsType_normal ipsType_richText ipsContained ipsType_break ipsSpacer_both'>
	{{if count($articles)}}
		{{foreach $articles as $id => $record}}
			{template="entry" app="cms" location="database" group="category_articles" params="$record, $database"}
		{{endforeach}}
	{{endif}}
</section>
{{if $database->featured_settings['pagination'] and ( $pagination['pages'] > 1 )}}
	{template="pagination" app="core" location="global" group="global" params="$url, $pagination['pages'], $pagination['page'], $database->featured_settings['perpage'], TRUE, 'page'"}
{{endif}}