<ips:template parameters="$item, $comment, $editorName, $app, $type, $class=''" />
{{$idField = $comment::$databaseColumnId;}}
<div id='comment-{$comment->$idField}_wrap' data-controller='core.front.core.comment' data-commentApp='{$app}' data-commentType='{$type}' data-commentID="{$comment->$idField}" data-quoteData='{expression="json_encode( array('userid' => $comment->author()->member_id, 'username' => $comment->author()->name, 'timestamp' => $comment->mapped('date'), 'contentapp' => $app, 'contenttype' => $type, 'contentclass' => $class, 'contentid' => $item->id, 'contentcommentid' => $comment->$idField) )"}' class='ipsComment_content ipsType_medium'>
	
	<div class='ipsComment_header ipsPhotoPanel ipsPhotoPanel_mini'>
		{template="userPhoto" app="core" group="global" params="$comment->author(), 'mini', $comment->warningRef()"}
		<div>
			<p class='ipsPos_right ipsType_reset ipsType_blendLinks'>
				<a href='{$comment->item()->url()->setQueryString( array( 'do' => 'findComment', 'comment' => $comment->id ) )}' data-ipsTooltip title='{lang="share_this_comment"}' data-ipsMenu data-ipsMenu-closeOnClick='false' id='elShareComment_{$comment->id}'><i class='fa fa-share-alt'></i></a>
				{{if count( $item->commentMultimodActions() )}}
					<input type="checkbox" name="multimod[{$comment->$idField}]" value="1" data-role="moderation" data-actions="{{if $comment->canSplit()}}split merge{{endif}} {{if $comment->hidden() === -1 AND $comment->canUnhide()}}unhide{{elseif $comment->hidden() === 1 AND $comment->canUnhide()}}approve{{elseif $comment->canHide()}}hide{{endif}} {{if $comment->canDelete()}}delete{{endif}}">
				{{endif}}
			</p>
			<h3 class='ipsComment_author ipsType_blendLinks'>
				<strong class='ipsType_normal'>{template="userLink" app="core" group="global" params="$comment->author(), $comment->warningRef()"}</strong>
				{template="reputationBadge" group="global" app="core" params="$comment->author()"}
			</h3>
			<p class='ipsComment_meta ipsType_light ipsType_medium'>
				{$comment->dateLine()|raw}
				{{if $comment->editLine()}}
					({lang="edited_lc"})
				{{endif}}
				{{if $comment->hidden()}}
					&middot; {$comment->hiddenBlurb()}
				{{endif}}
				{{if $comment instanceof \IPS\Content\ReportCenter and !\IPS\Member::loggedIn()->group['gbw_no_report'] and $comment->hidden() !== 1 }}
					&middot; <a href='{$comment->url('report')}' data-ipsDialog data-ipsDialog-remoteSubmit data-ipsDialog-size='medium' data-ipsDialog-flashMessage='{lang="report_submit_success"}' data-ipsDialog-title="{lang="report"}" data-action='reportComment' title='{lang="report_content"}'>{lang="report"}</a>
				{{endif}}
			</p>

			{{if member.modPermission('mod_see_warn') and $comment->warning}}
				{template="commentWarned" group="global" app="core" params="$comment"}
			{{endif}}
		</div>
	</div>
	<div class='ipsPad'>
		{{if in_array( 'IPS\Content\Reputation', class_implements( $comment ) ) and settings.reputation_highlight and $comment->reputation() >= settings.reputation_highlight}}
			<strong class='ipsComment_popularFlag' data-ipsTooltip title='{lang="this_is_a_popular_comment"}'><i class='fa fa-star'></i></strong>
		{{endif}}
		
		<div data-role='commentContent' class='ipsType_normal ipsType_richText ipsType_break ipsContained' data-controller='core.front.core.lightboxedImages'>
			{{if $comment->hidden() === 1 && $comment->author()->member_id == \IPS\Member::loggedIn()->member_id}}
				<strong class='ipsType_medium ipsType_warning'><i class='fa fa-info-circle'></i> {lang="comment_awaiting_approval"}</strong>
			{{endif}}
			{$comment->content()|raw}
			
			{{if $comment->editLine()}}
				{$comment->editLine()|raw}
			{{endif}}
		</div>
		
		{{if $comment->hidden() !== 1 && $comment instanceof \IPS\Content\Reputation and settings.reputation_enabled}}
			{template="reputation" group="global" app="core" params="$comment, 'ipsPos_right ipsResponsive_noFloat'"}
		{{endif}}

		<ul class='ipsComment_controls ipsClearfix' data-role="commentControls">
			{{if $comment->hidden() === 1 && ( $comment->canUnhide() || $comment->canDelete() )}}
				{{if $comment->canUnhide()}}
					<li><a href='{$comment->url('unhide')->csrf()}' class='ipsButton ipsButton_verySmall ipsButton_positive' data-action='approveComment'><i class='fa fa-check'></i> {lang="approve"}</a></li>
				{{endif}}
				{{if $comment->canDelete()}}
					<li><a href='{$comment->url('delete')->csrf()}' data-confirm data-action='deleteComment' data-updateOnDelete="#commentCount" class='ipsButton ipsButton_verySmall ipsButton_negative'><i class='fa fa-times'></i> {lang="delete"}</a></li>
				{{endif}}
				{{if $comment->canEdit() || $comment->canSplit()}}
					<li>
						<a href='#elControls_{$comment->$idField}_menu' id='elControls_{$comment->$idField}' data-ipsMenu data-ipsMenu-appendTo='#comment-{$comment->$idField}_wrap'>{lang="options"} &nbsp;<i class='fa fa-caret-down'></i></a>
						<ul id='elControls_{$comment->$idField}_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							{{if $comment->canEdit()}}
								{{if $comment->mapped('first') and $comment->item()->canEdit()}}
									<li class='ipsMenu_item'><a href='{$comment->item()->url()->setQueryString( 'do', 'edit' )}'>{lang="edit"}</a></li>
								{{else}}
									<li class='ipsMenu_item'><a href='{$comment->url('edit')}' data-action='editComment'>{lang="edit"}</a></li>
								{{endif}}
							{{endif}}
							{{if $comment->canSplit()}}
								<li class='ipsMenu_item'><a href='{$comment->url('split')}' data-action='splitComment' data-ipsDialog data-ipsDialog-title="{lang="split_to_new" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $item::$title )"}">{lang="split"}</a></li>
							{{endif}}
						</ul>
					</li>
				{{endif}}
			{{else}}
				{{if $comment->hidden() === 0 and $item->canComment() and $editorName}}
					<li data-ipsQuote-editor='{$editorName}' data-ipsQuote-target='#comment-{$comment->$idField}' class='ipsJS_show'>
						<button class='ipsButton ipsButton_light ipsButton_verySmall ipsButton_narrow cMultiQuote ipsHide' data-action='multiQuoteComment' data-ipsTooltip data-ipsQuote-multiQuote data-mqId='mq{$comment->$idField}' title='{lang="multiquote"}'><i class='fa fa-plus'></i></button>
					</li>
					<li data-ipsQuote-editor='{$editorName}' data-ipsQuote-target='#comment-{$comment->$idField}' class='ipsJS_show'>
						<a href='#' data-action="quoteComment" data-ipsQuote-singleQuote>{lang="quote"}</a>
					</li>
				{{endif}}
				{{if $comment->canEdit()}}
					{{if $comment->mapped('first') and $comment->item()->canEdit()}}
						<li><a href='{$comment->item()->url()->setQueryString( 'do', 'edit' )}'>{lang="edit"}</a></li>
					{{else}}
						<li><a href='{$comment->url('edit')}' data-action='editComment'>{lang="edit"}</a></li>
					{{endif}}
				{{endif}}
				{{if $comment->canDelete() || $comment->canSplit() || ( $comment instanceof \IPS\Content\Hideable AND ( ( !$comment->hidden() and $comment->canHide() ) || ( $comment->hidden() and $comment->canUnhide() ) ) )}}
					<li>
						<a href='#elControls_{$comment->$idField}_menu' id='elControls_{$comment->$idField}' data-ipsMenu data-ipsMenu-appendTo='#comment-{$comment->$idField}_wrap'>{lang="options"} &nbsp;<i class='fa fa-caret-down'></i></a>
						<ul id='elControls_{$comment->$idField}_menu' class='ipsMenu ipsMenu_narrow ipsHide'>
							{{if $comment instanceof \IPS\Content\Hideable}}
								{{if !$comment->hidden() and $comment->canHide()}}
									<li class='ipsMenu_item'><a href='{$comment->url('hide')->csrf()}' data-ipsDialog data-ipsDialog-title="{lang="hide"}">{lang="hide"}</a></li>
								{{elseif $comment->hidden() and $comment->canUnhide()}}
									<li class='ipsMenu_item'><a href='{$comment->url('unhide')->csrf()}'>{lang="unhide"}</a></li>
								{{endif}}
							{{endif}}
							{{if $comment->canSplit()}}
								<li class='ipsMenu_item'><a href='{$comment->url('split')}' data-action='splitComment' data-ipsDialog data-ipsDialog-title="{lang="split_to_new" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $item::$title )"}">{lang="split"}</a></li>
							{{endif}}
							{{if $comment->canDelete()}}
								<li class='ipsMenu_item'><a href='{$comment->url('delete')->csrf()}' data-action='deleteComment' data-updateOnDelete="#commentCount">{lang="delete"}</a></li>
							{{endif}}
						</ul>
					</li>
				{{endif}}
			{{endif}}
			<li class='ipsHide' data-role='commentLoading'>
				<i class='icon-spinner2 ipsLoading_tinyIcon'></i>
			</li>
		</ul>
	</div>

	<div class='ipsMenu ipsMenu_wide ipsHide cPostShareMenu' id='elShareComment_{$comment->id}_menu'>
		<div class='ipsPad'>
			<h4 class='ipsType_sectionHead'>{lang="share_this_comment"}</h4>
			<hr class='ipsHr'>
			<h5 class='ipsType_normal ipsType_reset'>{lang="link_to_comment"}</h5>
			<input type='text' value='{$comment->item()->url()->setQueryString( array( 'do' => 'findComment', 'comment' => $comment->id ) )}' class='ipsField_fullWidth'>
		</div>
	</div>
</div>