<ips:template parameters="$content, $extraClass='', $forceType=NULL, $countOnly=FALSE" />

{{if $content instanceof \IPS\Content\Reputation and settings.reputation_enabled}}
	<div data-controller='core.front.core.reputation' class='ipsRep_mini {{if $extraClass}}{$extraClass}{{endif}}'>
		{{if settings.reputation_point_types == 'like'}}
			<div class='ipsLikeRep'>
				{{if member.group['gbw_view_reps']}}
					<a href='{$content->url( 'showRep' )}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="like_log_title"}' data-ipsTooltip class='ipsReputation_count {{if intval( $content->reputation() ) === 0}}ipsType_light{{else}}ipsType_blendLinks{{endif}}'><i class='fa fa-heart ipsType_small'></i> {$content->reputation()}</a>
				{{else}}
					<span class='ipsReputation_count {{if $content->reputation() < 0}}ipsType_negative{{elseif $content->reputation() > 0}}ipsType_positive{{else}}ipsType_neutral{{endif}}'><i class='fa {{if $content->reputation() < 0}}fa-minus-circle{{elseif $content->reputation() > 0}}fa-plus-circle{{else}}fa-circle{{endif}} ipsType_small'></i> {$content->reputation()}</span>
				{{endif}}
				{{if $content->canGiveReputation( 1 ) && !$countOnly}}
					&nbsp;&nbsp;<a href='{$content->url( 'rep' )->setQueryString( 'rep', 1 )->setQueryString( 'mini', 1 )}' data-action="giveReputation">{lang="like"}</a>
				{{endif}}
				{{if $content->canGiveReputation( -1 ) && !$countOnly}}
					&nbsp;&nbsp;<a href='{$content->url( 'rep' )->setQueryString( 'rep', -1 )->setQueryString( 'mini', 1 )}' data-action="giveReputation">{lang="unlike"}</a>
				{{endif}}
			</div>
		{{else}}
			<div class='ipsLikeRep'>
				{{if $content->canGiveReputation( 1 ) && !$countOnly}}
					<a href='{$content->url( 'rep' )->setQueryString( 'rep', 1 )->setQueryString( 'mini', 1 )}' data-action="giveReputation" class='ipsButton ipsButton_rep ipsButton_repUp'><i class='fa fa-arrow-up'></i></a>
				{{endif}}
				{{if $content->canGiveReputation( -1 ) && !$countOnly}}
					<a href='{$content->url( 'rep' )->setQueryString( 'rep', -1 )->setQueryString( 'mini', 1 )}' data-action="giveReputation" class='ipsButton ipsButton_rep ipsButton_repDown'><i class='fa fa-arrow-down'></i></a>
				{{endif}}
				
				{{if settings.reputation_show_content}}
					{{if member.group['gbw_view_reps']}}
						<a href='{$content->url( 'showRep' )}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title='{lang="rep_log_title"}' title='{lang="see_who_repped"}' data-ipsTooltip class='ipsReputation_count {{if $content->reputation() < 0}}ipsType_negative{{elseif $content->reputation() > 0}}ipsType_positive{{else}}ipsType_neutral{{endif}}'><i class='fa {{if $content->reputation() < 0}}fa-minus-circle{{elseif $content->reputation() > 0}}fa-plus-circle{{else}}fa-circle{{endif}} ipsType_small'></i> {$content->reputation()}</a>
					{{else}}
						<span class='ipsReputation_count {{if $content->reputation() < 0}}ipsType_negative{{elseif $content->reputation() > 0}}ipsType_positive{{else}}ipsType_neutral{{endif}}'><i class='fa {{if $content->reputation() < 0}}fa-minus-circle{{elseif $content->reputation() > 0}}fa-plus-circle{{else}}fa-circle{{endif}} ipsType_small'></i> {$content->reputation()}</span>
					{{endif}}
				{{endif}}
			</div>
		{{endif}}
	</div>
{{endif}}
