<ips:template parameters="$member, $size='small', $warningRef=NULL, $classes='', $hovercard=TRUE" />
{{if $member->member_id and \IPS\Member::loggedIn()->canAccessModule( \IPS\Application\Module::get( 'core', 'members' ) )}}
	<a href="{{if $warningRef}}{$member->url()->setQueryString( 'wr', $warningRef )}{{else}}{$member->url()}{{endif}}" {{if $hovercard}}data-ipsHover data-ipsHover-target="{$member->url()->setQueryString( 'do', 'hovercard' )}"{{endif}} class="ipsUserPhoto ipsUserPhoto_{$size} {{if $classes}}{$classes}{{endif}}" title="{lang="view_user_profile" sprintf="$member->name"}">
		<img src='{$member->photo}' alt=''>
	</a>
{{else}}
	<span class='ipsUserPhoto ipsUserPhoto_{$size} {{if $classes}}{$classes}{{endif}}'>
		<img src='{$member->photo}' alt=''>
	</span>
{{endif}}