<ips:template parameters="$latestSpiderHits, $spiderGraphStats" />
<div class="">
	{$spiderGraphStats|raw}
</div>
<br>

<div class='ipsGrid'>
	<div class='ipsGrid_span12'>
		<div class="acpBlock ipsClear">
			<div class='ipsClearfix ipsClear ipsPad_half ipsAreaBackground_dark'>
				<h2>{lang="latest_spider_visits"}</h2>
			</div>
			<table class='ipsTable ipsTable_responsive ipsTable_zebra' data-role="table" data-ipsKeyNav data-ipsKeyNav-observe='e d return'>
				<thead>
					<tr class='ipsAreaBackground'>
						<th>{lang="search_engine"}</th>
						<th>{lang="date"}</th>
						<th>{lang="page_visited"}</th>
					</tr>
				</thead>
				<tbody data-role="tableRows">
					{{foreach $latestSpiderHits as $hit}}
						<tr>
							<td>{lang="useragent-{$hit['bot']}"}</td>
							<td>{datetime="$hit['entry_date']"}</td>
							<td>{template="truncatedUrl" app="core" group="global" location="global" params="$hit['request_addr']"}</td>
						</tr>
					{{endforeach}}
					<tr>
						<td colspan='5' class='ipsAreaBackground ipsType_center'>
							<a href='{url="app=core&module=promotion&controller=seo&do=spiderLogs"}' class='ipsButton ipsButton_primary'>{lang="view_all"}</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>