<ips:template parameters="$value" />
<div class="ipsClearFix">
	<table class='ipsTable'>
		<tr>
			<td class="field_title">
				<strong class="title">{lang="ftp_display_protocol"}</strong>
			</td>
			<td class="field_field">
				{$value['protocol']}
			</td>
		</tr>
		<tr>
			<td class="field_title">
				<strong class="title">{lang="ftp_display_hostname"}</strong>
			</td>
			<td class="field_field">
				{$value['server']}
			</td>
		</tr>
		<tr>
			<td class="field_title">
				<strong class="title">{lang="ftp_display_port"}</strong>
			</td>
			<td class="field_field">
				{$value['port']}
			</td>
		</tr>
		<tr>
			<td class="field_title">
				<strong class="title">{lang="ftp_display_path"}</strong>
			</td>
			<td class="field_field">
				{$value['path']}
			</td>
		</tr>
		<tr>
			<td class="field_title">
				<strong class="title">{lang="ftp_display_username"}</strong>
			</td>
			<td class="field_field">
				{$value['un']}
			</td>
		</tr>
		<tr>
			<td class="field_title">
				<strong class="title">{lang="ftp_display_password"}</strong>
			</td>
			<td class="field_field">
				{$value['pw']}
			</td>
		</tr>
	</table>
</div>